---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`1 + 0` vale `10`"
  checked: false
- value: "`1 + 0` vale `True`"
  checked: false
- value: '`"1" +  "1"` vale `"2"`'
  checked: false
- value: "`True or False` vale `True`"
  checked: true
- value: "`40 + 0.4` vale `44`"
  checked: false
- value: Ninguna es verdadera
  checked: false
name: No tan iguales
