---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '"hola" es un string'
  checked: true
- value: 4 es un número
  checked: true
- value: '"4" es un número'
  checked: false
- value: '"True" es un booleano'
  checked: false
- value: 0 es un booleano
  checked: false
- value: Ninguna es verdadera
  checked: false
name: Tipos de datos
