---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '`len("______") == 16`'
  checked: false
- value: '`len("______") <= 3`'
  checked: false
- value: '`"â" in "______" or "Â" in "______"`'
  checked: false
- value: '`"ë" in str.lower("______")`'
  checked: false
- value: '`" " in "______"`'
  checked: false
- value: '`str.startswith("______", "Xo")`'
  checked: false
- value: '`str.startswith("Xo", "______")`'
  checked: false
- value: Ninguna es verdadera
  checked: true
name: Tu nombre
