---
locale: es
tags: []
layout: input_right
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`lower "PROGRAMAR"`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`lower("PROGRAMAR")`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`str.lower("PROGRAMAR")`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores
  checked: false
name: Nuevo ejercicio
