---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '`upper "python"`'
  checked: false
- value: '`upper("python")`'
  checked: false
- value: '`str.upper("python")`'
  checked: false
- value: Ninguna de las anteriores
  checked: true
name: Capitalización
