---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`upper "python"`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`upper("python")`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`str.upper("python")`'
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna de las anteriores
  checked: true
name: Capitalización
