---
locale: es
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: len("mesa") vale 4
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: len("True") vale 4
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: len(True) vale 4
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: len(4) vale 4
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: len("¡ey!") vale 4
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: len("oh no") vale 4
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Ninguna es verdadera
  checked: false
name: Longitudes
