---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '`len("mesa")` vale `4`'
  checked: true
- value: '`len("True")` vale `4`'
  checked: true
- value: "`len(True)` vale `4`"
  checked: false
- value: "`len(4)` vale `4`"
  checked: false
- value: '`len("¡ey!")` vale `4`'
  checked: true
- value: '`len("oh no")` vale `4`'
  checked: false
- value: Ninguna es verdadera
  checked: false
name: Longitudes
