---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '`lower "PROGRAMAR"`'
  checked: false
- value: '`lower("PROGRAMAR")`'
  checked: false
- value: '`str.lower("PROGRAMAR")`'
  checked: true
- value: Ninguna de las anteriores
  checked: false
name: Programita
